### ISSUE TITLE
Some Optimization needed for Forge (featuring suggestions)

### ISSUE THREAD

**Issue by Puncake12** [jam1garner/Smash-Forge#189] opened 2018-05-09 14:42 UTC
- Have hitboxes change on the fly instead of having to play the frame over again
- AMCD doesn't compile Set_Loops properly
- Characters with a heavy amount of FSMs can crash forge
- Add FAF as animation length to animation bar (older versions had it) and make FSMs change the animation length accordingly instead of looping the last frame until the vanila length ends.
- Forge can 'hiccup' at times
- It may just be my PC, but Forge crashes when using NVIDA Graphics Card
- Animations can be faster or slower at times

**Comment by ScanMountGoat** [comment] 2018-05-09 15:15
The crashing is due to issues with Nvidia's drivers. It works fine when tested on AMD and Intel integrated graphics.

**Comment by legoj15** [comment] 2018-05-09 15:58
Oh, I'm glad it's just not me with the crashes. Smash forge worked for me in February, so does that mean we have to wait until NVidia fixes the regression, or is there a hack that can be put in place?

**Comment by ScanMountGoat** [comment] 2018-05-09 17:15
Nvidia won't be changing their drivers. It should be fixed in Forge eventually. It's difficult to fix without being able to test on different hardware. You can build previous versions in visual studio.

**Closed** 2018-07-31 13:09 UTC
