### ISSUE TITLE
Viewport

### ISSUE THREAD

**Issue by smashguy** [jam1garner/Smash-Forge#4] opened 2016-10-03 08:26 UTC
Viewport goes out of view if window is left untouched for too long.

**Comment by Y2K-x** [comment] 2016-10-12 19:59
Currently that is not something we can exactly fix at this time. The issue here is that the viewport is technically still active when the window is minimized, so if you use the mouse wheel or anything, it gets zoomed out super far, just try zooming in and out a lot to get the viewport to pop back into view. Thanks!

**Comment by jam1garner** [comment] 2016-10-12 21:38
Reopening this issue until it's fixed, in the meantime hold tight

**Comment by Sammi-Husky** [comment] 2016-10-14 22:27
Fixed in docked-editors branch, will close when it's merged

**Comment by Sammi-Husky** [comment] 2016-10-15 08:45
fixed with baa2200

**Comment by Ploaj** [comment] 2016-10-17 14:56
Re-opening because the issue is still present

**Comment by Sammi-Husky** [comment] 2016-10-17 23:51
This problem comes from updating the mouse positions every frame in render. I tried to fix it (successfully) originally by moving mouse updates to the glControl's onMouseMove event handler (which only fires when the control is focused so we don't have to worry about MouseIsOverControl anymore either, and that fixed it. The only problem was that i couldn't update the mouse wheel for zoom there. This can probably be fixed by moving the zoom stuff to the OnMouseWheel event though

**Comment by Ploaj** [comment] 2016-12-20 04:22
This has been more or less fixed now :P 
Took us long enough, huh?

**Closed by Ploaj** 2016-12-20 04:22 UTC
