### ISSUE TITLE
Bone recreation breaks in-game. SMD-VBN

### ISSUE THREAD

**Issue by KillzXGaming** [jam1garner/Smash-Forge#19] opened 2016-11-20 16:29 UTC
I've ran into an issue where custom vbn files cause 
this:
![3](https://cloud.githubusercontent.com/assets/13475262/20464394/8c4fe358-af14-11e6-9fad-800561d394cb.gif)

This is the case for not just my custom made boneset. The default skeleton ones do this aswell. The way i made the smd was from wallworm and i exported it with these settings:
http://i.imgur.com/hStWkeF.png

Things to note:
VBN works fine in smash forge
Importing the vbn back works fine
Occurs with and without custom animations

Files being used
[Alolan Raichu Animated.zip](https://github.com/jam1garner/Smash-Forge/files/602148/Alolan.Raichu.Animated.zip)

My specs:
CPU i5 4670
GPU gtx 970
RAM 8gb
OS Windows 10

**Comment by Escope12** [comment] 2016-11-21 08:42
Has this problem happened in previous versions?

**Comment by KillzXGaming** [comment] 2016-11-21 17:25
It was an issue with bone order which ploaj help fix. Ploaj may need to implement some sort of bone ordering option within forge as others will have this issue for custom vbns.

**Comment by Escope12** [comment] 2016-11-21 17:49
Why did you close this issue @KillzXGaming?

**Comment by KillzXGaming** [comment] 2016-11-21 21:08
Ops by accident.

**Comment by Escope12** [comment] 2016-11-21 21:27
@KillzXGaming Are you on Discord?

**Comment by KillzXGaming** [comment] 2016-11-21 23:43
Yup

**Comment by Escope12** [comment] 2016-11-23 04:24
@KillzXGaming Have you had this issue? https://github.com/jam1garner/Smash-Forge/issues/3

**Comment by KillzXGaming** [comment] 2016-11-25 03:33
Some animations yeah but a good amount work fine.

**Comment by Escope12** [comment] 2016-11-25 06:18
Delfino Plaza'a animations don't play for some reason.

**Comment by Ploaj** [comment] 2016-12-20 04:21
This issue has been fixed now. Most other bone issues are probably caused by bone order.

**Closed by Ploaj** 2016-12-20 04:21 UTC
